apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notes
  namespace: notes
spec:
  rules:
    - host: notes.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: notes-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notes-frontend
                port:
                  number: 80
